### PR TITLE
Use API 2

### PR DESCRIPTION
**Pull request by goofyz**
Use API 2 ( documented in #2) to retrieve topics & post.

I did not read HKG for a long time after http://plasticnofd.xyz/ is dead. sosad

### CODE REVIEW

**Comment by mingchuno** [comment]
感動流涕！

**Comment by gaplo917** [comment]
+1 感動流涕 :+1:  !

**Comment by mingchuno** [comment]
己上production!

**Comment by goofyz** [comment]
Thanks! 終於可以睇高登 #love#

**Comment by Jasonlhy** [comment]
adoreeee

**Pull request merged**
