### PR TITLE
Parse [url] tag, Update Readme

### PR DESCRIPTION
**Pull request by Jasonlhy**
Parse [url] tag
Update Readme

### CODE REVIEW

**Comment by mingchuno** [comment]
Thank you very much! Not in HK right now. I'll deploy once I back to HK.

**Comment by mingchuno** [comment]
@Jasonlhy deployed into production

**Comment by Jasonlhy** [comment]
adore
不過唔知點解有時個API 唔係出`[url]` tag 而係直接`<a href="xxx">`

**Comment by mingchuno** [comment]
@Jasonlhy 高登policy, 佢有的url唔想直出比你click到

**Pull request merged**
